version: "3"
services:
  rest-number:
    image: "ahmethmo/rest-number:last"
    ports:
      - "8701:8701"
  rest-book:
    image: "ahmethmo/rest-book:last"
    ports:
      - "8702:8702"
    environment:
      - NUMBER_PROXY_MP_REST_URL=http://rest-number:8701